default: &default
  adapter: oracle_enhanced
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: //localhost:1521/xe
  username: sportflix_development
  password: test

test:
  <<: *default
  database: //localhost:1521/xe
  username: sportflix_test
  password: test

production:
  <<: *default
  database: sportflix_production
  username: sportflix
  password: <%= ENV['SPORTFLIX_DATABASE_PASSWORD'] %>
